# Generated by Django 5.2.4 on 2025-07-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0003_visitor_ip_address_visitor_visit_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='count',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
