# Generated by Django 5.2.4 on 2025-07-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0004_remove_visitor_count_alter_visitor_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='referer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
